# name: High Contrast
# fish_color_comment: comments
# fish_color_quote: strings
# fish_color_param: numbers and literals
# fish_color_operator: operators
# fish_color_command: functions and commands
# fish_color_normal: default foreground
# fish_color_status: status line
# fish_color_error: diagnostics
fish_color_comment brgreen --bold
fish_color_quote bryellow --bold
fish_color_param brcyan
fish_color_operator bryellow --bold
fish_color_command brblue --bold
fish_color_normal brwhite
fish_color_error brred --bold
